### ISSUE TITLE
Resulten moeten onder elkaar worden neergeplaatst

### ISSUE THREAD

**Issue by AllyssaA** [Hoa0/Laagdrempelig-zoeken#35]
Op dit moment verdwijnt de zoek geschiedenis. De bedoeling is dat elke zoek resultaat onder in de chat opnieuw in laad en niet vervangen wordt.

**Comment by Hoa0** [comment]
Resultaten worden nu wel weergegeven onder elkaar. Bij de catalogus gaat dat ook goed met feedback van "oba assistent". Bij het zoeken krijg je ook de resultaten onder elkaar. Alleen de feedback "oba assistent" komt steeds eronder te staan.
